"""empty message

Revision ID: 5e296d785e8c
Revises: 72942716f9da
Create Date: 2024-08-13 20:05:23.532020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e296d785e8c'
down_revision = '72942716f9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepted', sa.Boolean(), nullable=True))
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_accepted')

    # ### end Alembic commands ###
